-- LeadFlow AI — Neon Database Schema (v0.2)
-- SaaS Agents IA de prospecting pour le marché africain

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- EXISTING TABLES (kept from v0.1)
-- ============================================

-- Users (PME / devs accounts)
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL DEFAULT '',
  full_name VARCHAR(255),
  company VARCHAR(255),
  role VARCHAR(50) DEFAULT 'user',
  plan VARCHAR(20) DEFAULT 'free',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Leads (existing)
CREATE TABLE IF NOT EXISTS leads (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  company VARCHAR(255),
  phone VARCHAR(50),
  source VARCHAR(100) DEFAULT 'landing',
  score INTEGER DEFAULT 0,
  status VARCHAR(20) DEFAULT 'new',
  budget VARCHAR(100),
  need TEXT,
  timeline VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Appointments (existing)
CREATE TABLE IF NOT EXISTS appointments (
  id SERIAL PRIMARY KEY,
  lead_id INTEGER REFERENCES leads(id),
  scheduled_at TIMESTAMP NOT NULL,
  duration INTEGER DEFAULT 30,
  status VARCHAR(20) DEFAULT 'pending',
  meeting_link TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Qualification responses (existing)
CREATE TABLE IF NOT EXISTS qualifications (
  id SERIAL PRIMARY KEY,
  lead_id INTEGER REFERENCES leads(id),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  score_weight INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- NEW TABLES — Credit System
-- ============================================

-- Credit balances (one per user)
CREATE TABLE IF NOT EXISTS credit_balances (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  balance INTEGER NOT NULL DEFAULT 10,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Credit transactions (history of all credit movements)
CREATE TABLE IF NOT EXISTS credit_transactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL, -- positive = purchase/bonus, negative = usage
  type VARCHAR(50) NOT NULL, -- 'signup_bonus', 'purchase', 'agent_run', 'refund'
  description VARCHAR(500),
  reference_id VARCHAR(255), -- agent_run id or payment reference
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- NEW TABLES — AI Agents
-- ============================================

-- Agents catalog (the 6 prospecting agents)
CREATE TABLE IF NOT EXISTS agents (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  icon VARCHAR(50),
  credit_cost INTEGER NOT NULL DEFAULT 1,
  category VARCHAR(50) DEFAULT 'prospecting',
  system_prompt TEXT,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Agent runs (log of agent executions)
CREATE TABLE IF NOT EXISTS agent_runs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  agent_id INTEGER NOT NULL REFERENCES agents(id),
  input JSONB,
  output JSONB,
  credits_consumed INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending', -- pending, running, completed, failed
  error TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

-- ============================================
-- NEW TABLES — Prospecting
-- ============================================

-- Campaigns (prospecting campaigns)
CREATE TABLE IF NOT EXISTS campaigns (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  agent_id INTEGER REFERENCES agents(id),
  status VARCHAR(20) DEFAULT 'draft', -- draft, active, paused, completed
  target_criteria JSONB, -- industry, company_size, location, role, etc.
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Prospects (enriched leads tied to campaigns)
CREATE TABLE IF NOT EXISTS prospects (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  campaign_id INTEGER REFERENCES campaigns(id) ON DELETE SET NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  company VARCHAR(255),
  phone VARCHAR(50),
  linkedin_url VARCHAR(500),
  source VARCHAR(100) DEFAULT 'agent',
  score INTEGER DEFAULT 0,
  status VARCHAR(20) DEFAULT 'new', -- new, qualified, contacted, replied, won, lost
  data JSONB, -- extra data from agent (industry, role, etc.)
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Outreach messages (generated by agents)
CREATE TABLE IF NOT EXISTS outreach_messages (
  id SERIAL PRIMARY KEY,
  prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) DEFAULT 'email', -- email, linkedin, twitter
  subject VARCHAR(500),
  content TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'draft', -- draft, sent, replied, bounced
  sent_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================

-- Existing indexes
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON leads(user_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_score ON leads(score DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_lead_id ON appointments(lead_id);
CREATE INDEX IF NOT EXISTS idx_qualifications_lead_id ON qualifications(lead_id);

-- New indexes
CREATE INDEX IF NOT EXISTS idx_credit_balances_user_id ON credit_balances(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_id ON credit_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_created ON credit_transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_user_id ON agent_runs(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_agent_id ON agent_runs(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_created ON agent_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaigns_user_id ON campaigns(user_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_prospects_user_id ON prospects(user_id);
CREATE INDEX IF NOT EXISTS idx_prospects_campaign_id ON prospects(campaign_id);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects(status);
CREATE INDEX IF NOT EXISTS idx_outreach_prospect_id ON outreach_messages(prospect_id);
CREATE INDEX IF NOT EXISTS idx_outreach_user_id ON outreach_messages(user_id);

-- ============================================
-- SEED DATA — Default Agents
-- ============================================

INSERT INTO agents (name, slug, description, icon, credit_cost, category, system_prompt, sort_order) VALUES
(
  'Lead Finder',
  'lead-finder',
  'Trouve des prospects qualifiés selon vos critères : industrie, taille d''entreprise, localisation, rôle. Idéal pour bâtir une liste de prospects ciblés.',
  'Search',
  5,
  'prospecting',
  'Tu es un expert en lead generation B2B. À partir des critères fournis (industrie, localisation, taille d''entreprise, rôle cible), tu génères une liste de prospects potentiels avec leur nom, entreprise, rôle et justification du fit.',
  1
),
(
  'Cold Email Writer',
  'cold-email-writer',
  'Génère des emails de prospection personnalisés et optimisés pour chaque prospect. Augmente votre taux de réponse.',
  'Mail',
  2,
  'outreach',
  'Tu es un copywriter expert en cold email B2B. À partir des informations sur le prospect et l''offre, tu écris un email court, personnalisé et convainquant. Sujet accrocheur, corps concis (max 120 mots), CTA clair. Pas de jargon, pas de superlatifs.',
  2
),
(
  'Follow-up Sequencer',
  'follow-up-sequencer',
  'Crée des séquences de relance automatiques (3 à 5 emails) pour maximiser le taux de conversion de vos prospects.',
  'Repeat',
  8,
  'outreach',
  'Tu es un expert en séquences d''email de relance B2B. Tu crées une séquence de 3 à 5 emails de relance espacés dans le temps, chacun avec un angle différent (rappel, valeur, cas client, break-up). Chaque email doit être court et naturel.',
  3
),
(
  'Prospect Qualifier',
  'prospect-qualifier',
  'Analyse et score vos prospects (hot, warm, cold) selon leur fit avec votre offre. Priorisez les meilleurs leads.',
  'Target',
  3,
  'prospecting',
  'Tu es un expert en qualification de leads B2B. À partir des informations du prospect et des critères de l''ICP (Ideal Customer Profile), tu attribues un score de 0 à 100, un statut (hot/warm/cold) et une justification détaillée.',
  4
),
(
  'LinkedIn Outreach',
  'linkedin-outreach',
  'Génère des messages LinkedIn personnalisés pour le social selling. Connexion, follow-up, et value proposition.',
  'Linkedin',
  2,
  'outreach',
  'Tu es un expert en outreach LinkedIn B2B. À partir des informations sur le prospect et l''offre, tu écris un message LinkedIn de connexion court (max 300 caractères) et un message de suivi (value proposition). Pas de pitch, pas de spam.',
  5
),
(
  'Reply Handler',
  'reply-handler',
  'Analyse les réponses de vos prospects, les catégorise (intéressé, pas intéressé, out of office) et suggère la meilleure action.',
  'MessageSquareReply',
  1,
  'outreach',
  'Tu es un expert en gestion de réponses B2B. À partir du message reçu d''un prospect, tu le catégorises (intéressé / pas intéressé / out of office / à recontacter plus tard) et tu suggères la meilleure réponse à envoyer.',
  6
)
ON CONFLICT (slug) DO NOTHING;
